### ISSUE TITLE
traefik CreateContainerConfigError

### ISSUE THREAD

**Issue by sruckh** [sleighzy/k3s-traefik-v2-kubernetes-crd#22] opened 2021-03-16 07:50 UTC
I edited the secrets file and the two files to disable app-armor.  Upon applying each .yaml file in order I get the following output from `kubectl get pods`.

NAMESPACE     NAME                                      READY   STATUS
kube-system   traefik-7cb54d4966-t2g6w                  0/1     CreateContainerConfigError

This is after a clean install of ubuntu 20.04 x86_64 on rpi4, and installing k3s from script (curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --disable traefik) .

I am assuming that is problematic???

**Comment by sleighzy** [comment] 2021-03-16 09:00
Hi @sruckh . Can you provide the contents of the secrets file you edited, you can `xxxxx` out any items that shouldn't be shared. Can you also try the below commands to see if they provide any further info as the cause:

`kubectl get events -n kube-system`
`kubectl describe deployment/traefik -n kube-system`

Check if the contents of the secrets are as expected, e.g. to display the `traefik-basic-auth` secret.

`kubectl get secret traefik-basic-auth -n kube-system -o jsonpath='{.data}'`

**Comment by sleighzy** [comment] 2021-03-16 09:09
> ...and the two files to disable app-armor.

I'm running Traefik on my rpi4 cluster with app-armor enabled as well if you wanted to leave that on.

**Comment by sruckh** [comment] 2021-03-16 18:56
On 2021-03-16 02:00, Simon Leigh wrote:

> Hi @sruckh [1] . Can you provide the contents of the secrets file you 
> edited, you can xxxxx out any items that shouldn't be shared. Can you 
> also try the below commands to see if they provide any further info as 
> the cause:
> 
> kubectl get events -n kube-system
> kubectl describe deployment/traefik -n kube-system
> 
> Check if the contents of the secrets are as expected, e.g. to display 
> the traefik-basic-auth secret.
> 
> kubectl get secret traefik-basic-auth -n kube-system -o 
> jsonpath='{.data}'
> 
> --

Apparently I needed to do some more editing.

***@***.***:~$ kubectl get events -n kube-system
LAST SEEN   TYPE      REASON   OBJECT                         MESSAGE
25m         Warning   Failed   pod/traefik-7cb54d4966-t2g6w   Error: 
secret "godaddy" not found
19s         Normal    Pulled   pod/traefik-7cb54d4966-t2g6w   Container 
image "traefik:v2.4" already present on machine

***@***.***:~/k3s-traefik-v2-kubernetes-crd$ kubectl describe 
deployment/traefik -n kube-system
Name:                   traefik
Namespace:              kube-system
CreationTimestamp:      Tue, 16 Mar 2021 00:31:00 -0700
Labels:                 app=traefik
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=traefik
Replicas:               1 desired | 1 updated | 1 total | 0 available | 
1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
   Labels:           app=traefik
   Service Account:  traefik-ingress-controller
   Containers:
    traefik:
     Image:       traefik:v2.4
     Ports:       8080/TCP, 8443/TCP, 9080/TCP
     Host Ports:  0/TCP, 0/TCP, 0/TCP
     Args:
       --api.dashboard=true
       --ping=true
       --accesslog
       --entrypoints.traefik.address=:9080
       --entrypoints.web.address=:8080
       --entrypoints.websecure.address=:8443
       --providers.kubernetescrd
       --providers.kubernetesingress
       ***@***.***
       
--certificatesresolvers.godaddy.acme.storage=/etc/traefik/certs/acme.json
       --certificatesResolvers.godaddy.acme.dnsChallenge.provider=godaddy
       
--certificatesResolvers.godaddy.acme.dnsChallenge.delayBeforeCheck=0
       --log
       --log.level=INFO
     Limits:
       cpu:     1
       memory:  100Mi
     Liveness:  http-get http://:9080/ping delay=10s timeout=3s 
period=10s #success=1 #failure=3
     Environment:
       GODADDY_API_KEY:     <set to the key 'GODADDY_API_KEY' in secret 
'godaddy'>     Optional: false
       GODADDY_API_SECRET:  <set to the key 'GODADDY_API_SECRET' in 
secret 'godaddy'>  Optional: false
     Mounts:
       /etc/traefik/certs from certificates (rw)
   Volumes:
    certificates:
     Type:       PersistentVolumeClaim (a reference to a 
PersistentVolumeClaim in the same namespace)
     ClaimName:  traefik-certs-pvc
     ReadOnly:   false
Conditions:
   Type           Status  Reason
   ----           ------  ------
   Available      False   MinimumReplicasUnavailable
   Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  <none>
NewReplicaSet:   traefik-7cb54d4966 (1/1 replicas created)
Events:          <none>

***@***.***:~/k3s-traefik-v2-kubernetes-crd$ cat 
002-secrets.yaml
---
# https://developer.godaddy.com/keys/
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
   name: cloudflare
   namespace: kube-system
type: Opaque
data:
   CF_API_TOKEN: endxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==
   CF_EMAIL:  Y2XXXXXXXXXXXXXXXXXXXXXXXXXXXX==
---
# https://docs.traefik.io/middlewares/basicauth/#users
# Note: in a kubernetes secret the string (e.g. generated by htpasswd) 
must be base64-encoded first.
# To create an encoded user:password pair, the following command can be 
used:
# htpasswd -nb user password | openssl base64
apiVersion: v1
kind: Secret
metadata:
   name: traefik-basic-auth
   namespace: kube-system
data:
   users: |2
     dWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==

The output from the last command was this:
{"users":"SAME base64 string that was in secrets file"}

Seems I missed some stuff elsewhere that uses the GoDaddy stuff.

I am setting all this up for the first time, so massive learning curve 
going on right now.  Basically setting all this up so I can learn more 
about this environment.  Specifically kubernetes and containers, and now 
that I have been looking at this stuff the Ingress Controller.  Learning 
something new every day.

Thank You for looking.

Links:
------
[1] https://github.com/sruckh

**Comment by sleighzy** [comment] 2021-03-16 19:14
Thanks for that. Looks like you're using CloudFlare instead of GoDaddy so you need to update your `005-deployment.yaml` to match your `002-secrets.yaml`. In your secrets file you've changed the secret name to `cloudflare` and different key names, these don't match the ones in the deploy file. The deploy file would need to be changed to have something like this instead of the godaddy env vars so that it matches:

```
         env:
           - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: CF_API_TOKEN
            - name: CF_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: CF_EMAIL
```

**Comment by sleighzy** [comment] 2021-03-16 19:18
On a side note; I also run an Ubuntu 20.04 64bit Raspberry Pi 4 K3s cluster like yourself. Have a look at my https://github.com/sleighzy/raspberry-pi-k3s-homelab Github repo, as well as some of my other K3s repos, as they may have helpful info in other areas.

**Comment by sruckh** [comment] 2021-03-16 19:27
On 2021-03-16 12:18, Simon Leigh wrote:

> On a side note; I also run an Ubuntu 20.04 64bit Raspberry Pi 4 K3s 
> cluster like yourself. Have a look at my 
> https://github.com/sleighzy/raspberry-pi-k3s-homelab Github repo, as 
> well as some of my other K3s repos, as they may have helpful info in 
> other areas.
> 
> --

Thank you for the advice and help.  Yes, I have been reading all of your 
different repos.  I have gone through several different guides, and 
settled your guides as they seemed to be complete and match what I am 
trying to accomplish.

**Comment by sleighzy** [comment] 2021-03-26 04:01
Hi @sruckh   I’m going to close this issue off as looked to be a config issue on your end. Feel free to reach out if you’re still having issues and need further assistance in troubleshooting.

**Closed by sleighzy** 2021-03-26 04:01 UTC
